// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEJ7YT2geebWSQdRi4dS7KUu7G5PuxIQ',
    appId: '1:406021837694:android:0d2941eb2c06f5d5e5192f',
    messagingSenderId: '406021837694',
    projectId: 'cryptofeed-a032c',
    storageBucket: 'cryptofeed-a032c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3CwK-VGL8a05dP0MKMntR7PSATfkyTKw',
    appId: '1:406021837694:ios:f2999d46a783fc7ae5192f',
    messagingSenderId: '406021837694',
    projectId: 'cryptofeed-a032c',
    storageBucket: 'cryptofeed-a032c.appspot.com',
    iosClientId: '406021837694-s86r1b1lpsg2u0k128t4e11clefqtm95.apps.googleusercontent.com',
    iosBundleId: 'CryptoFeed',
  );
}
